name: publish-docker-image

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - "main"
jobs:
  build-and-push:
    name: publish-to-dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: stefanwin/stwgt-dev:latest
